use_frameworks!
platform :ios, '9.0'

target 'WDayDayCook' do

pod 'SnapKit' ## 自动布局
pod 'Alamofire' ## 网络请求, swift版的AFN
pod 'Kingfisher' ## 轻量级的SDWebImage
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'ObjectMapper'
pod 'SDCycleScrollView'
pod 'AlamofireObjectMapper'
end
